import type {
  CountryDefinition,
  IssueDefinition,
  ProductDefinition,
  ProductKey,
  RegionKey,
  TicketSource,
} from "./types.ts";

export const REFERENCE_DATE = "2026-05-31T12:00:00.000Z";
export const LOOKBACK_DAYS = 30;
export const DEFAULT_SEED = 20260531;

export const REGIONS: RegionKey[] = [
  "Nordics",
  "Europe",
  "North America",
  "LATAM",
  "MEA",
  "APAC",
];

export const SOURCES: TicketSource[] = ["Zendesk", "Salesforce"];

export const PRODUCTS: ProductDefinition[] = [
  {
    key: "Aico",
    label: "Aico",
    description: "Financial close automation and record-to-report orchestration.",
  },
  {
    key: "AARO",
    label: "AARO",
    description: "Complex group consolidation, disclosure, and regulatory reporting.",
  },
  {
    key: "Mercur",
    label: "Mercur",
    description: "Driver-based planning, forecasting, and performance management.",
  },
];

const countriesByRegion: Record<RegionKey, Array<[string, string]>> = {
  Nordics: [
    ["SE", "Sweden"],
    ["NO", "Norway"],
    ["FI", "Finland"],
    ["DK", "Denmark"],
    ["IS", "Iceland"],
    ["EE", "Estonia"],
    ["LV", "Latvia"],
    ["LT", "Lithuania"],
  ],
  Europe: [
    ["GB", "United Kingdom"],
    ["IE", "Ireland"],
    ["DE", "Germany"],
    ["FR", "France"],
    ["NL", "Netherlands"],
    ["BE", "Belgium"],
    ["LU", "Luxembourg"],
    ["CH", "Switzerland"],
    ["AT", "Austria"],
    ["PL", "Poland"],
    ["CZ", "Czechia"],
    ["SK", "Slovakia"],
    ["HU", "Hungary"],
    ["RO", "Romania"],
    ["BG", "Bulgaria"],
    ["GR", "Greece"],
    ["PT", "Portugal"],
    ["ES", "Spain"],
    ["IT", "Italy"],
    ["SI", "Slovenia"],
    ["HR", "Croatia"],
    ["RS", "Serbia"],
    ["UA", "Ukraine"],
    ["MD", "Moldova"],
    ["AL", "Albania"],
    ["ME", "Montenegro"],
    ["BA", "Bosnia and Herzegovina"],
    ["MK", "North Macedonia"],
    ["GE", "Georgia"],
    ["AM", "Armenia"],
    ["CY", "Cyprus"],
    ["MT", "Malta"],
    ["MC", "Monaco"],
    ["AD", "Andorra"],
    ["SM", "San Marino"],
    ["BY", "Belarus"],
  ],
  "North America": [
    ["US", "United States"],
    ["CA", "Canada"],
    ["MX", "Mexico"],
    ["CR", "Costa Rica"],
    ["PA", "Panama"],
    ["GT", "Guatemala"],
    ["DO", "Dominican Republic"],
    ["JM", "Jamaica"],
  ],
  LATAM: [
    ["BR", "Brazil"],
    ["AR", "Argentina"],
    ["CL", "Chile"],
    ["CO", "Colombia"],
    ["PE", "Peru"],
    ["UY", "Uruguay"],
    ["PY", "Paraguay"],
    ["BO", "Bolivia"],
    ["EC", "Ecuador"],
    ["VE", "Venezuela"],
    ["SV", "El Salvador"],
    ["HN", "Honduras"],
    ["NI", "Nicaragua"],
    ["GY", "Guyana"],
    ["SR", "Suriname"],
    ["BB", "Barbados"],
  ],
  MEA: [
    ["AE", "United Arab Emirates"],
    ["SA", "Saudi Arabia"],
    ["QA", "Qatar"],
    ["BH", "Bahrain"],
    ["OM", "Oman"],
    ["KW", "Kuwait"],
    ["IL", "Israel"],
    ["TR", "Turkey"],
    ["JO", "Jordan"],
    ["LB", "Lebanon"],
    ["IQ", "Iraq"],
    ["EG", "Egypt"],
    ["MA", "Morocco"],
    ["TN", "Tunisia"],
    ["DZ", "Algeria"],
    ["ZA", "South Africa"],
    ["NG", "Nigeria"],
    ["KE", "Kenya"],
    ["GH", "Ghana"],
    ["ET", "Ethiopia"],
    ["TZ", "Tanzania"],
    ["UG", "Uganda"],
    ["RW", "Rwanda"],
    ["SN", "Senegal"],
    ["CI", "Ivory Coast"],
    ["CM", "Cameroon"],
    ["BW", "Botswana"],
    ["NA", "Namibia"],
    ["ZW", "Zimbabwe"],
    ["ZM", "Zambia"],
    ["MU", "Mauritius"],
    ["AO", "Angola"],
    ["MZ", "Mozambique"],
    ["MG", "Madagascar"],
    ["CD", "Democratic Republic of the Congo"],
    ["CG", "Republic of the Congo"],
    ["GA", "Gabon"],
    ["BJ", "Benin"],
    ["TG", "Togo"],
    ["ML", "Mali"],
    ["NE", "Niger"],
    ["BF", "Burkina Faso"],
    ["SL", "Sierra Leone"],
    ["LR", "Liberia"],
    ["MW", "Malawi"],
    ["SO", "Somalia"],
    ["SD", "Sudan"],
    ["DJ", "Djibouti"],
  ],
  APAC: [
    ["IN", "India"],
    ["JP", "Japan"],
    ["KR", "South Korea"],
    ["AU", "Australia"],
    ["NZ", "New Zealand"],
    ["SG", "Singapore"],
    ["MY", "Malaysia"],
    ["ID", "Indonesia"],
    ["TH", "Thailand"],
    ["VN", "Vietnam"],
    ["PH", "Philippines"],
    ["CN", "China"],
    ["HK", "Hong Kong"],
    ["TW", "Taiwan"],
    ["BD", "Bangladesh"],
    ["LK", "Sri Lanka"],
    ["PK", "Pakistan"],
    ["NP", "Nepal"],
    ["KH", "Cambodia"],
    ["LA", "Laos"],
    ["MM", "Myanmar"],
    ["MN", "Mongolia"],
    ["KZ", "Kazakhstan"],
    ["UZ", "Uzbekistan"],
    ["KG", "Kyrgyzstan"],
    ["BN", "Brunei"],
    ["FJ", "Fiji"],
    ["PG", "Papua New Guinea"],
    ["MV", "Maldives"],
    ["BT", "Bhutan"],
  ],
};

export const COUNTRIES: CountryDefinition[] = Object.entries(countriesByRegion).flatMap(
  ([region, countries]) =>
    countries.map(([code, name]) => ({
      code,
      name,
      region: region as RegionKey,
    })),
);

export const PRODUCT_WEIGHTS: Record<ProductKey, number> = {
  Aico: 0.38,
  AARO: 0.34,
  Mercur: 0.28,
};

export const REGION_VOLUME_MULTIPLIER: Record<RegionKey, number> = {
  Nordics: 1.28,
  Europe: 1.14,
  "North America": 1.07,
  LATAM: 0.86,
  MEA: 0.82,
  APAC: 1.06,
};

export const ISSUE_DEFINITIONS: IssueDefinition[] = [
  {
    issueType: "Month-end close sync failure",
    product: "Aico",
    category: "Close",
    baseHours: 6,
    slaTargetHours: 8,
    severity: "high",
    routeBias: "Engineering",
    defaultSummary: "ERP close jobs are failing to synchronize at month-end checkpoints.",
  },
  {
    issueType: "Journal approval workflow stall",
    product: "Aico",
    category: "Close",
    baseHours: 4,
    slaTargetHours: 8,
    severity: "medium",
    routeBias: "Support Operations",
    defaultSummary: "Approvers are not receiving or clearing journal workflow tasks.",
  },
  {
    issueType: "ERP connector authentication error",
    product: "Aico",
    category: "Integration",
    baseHours: 8,
    slaTargetHours: 12,
    severity: "high",
    routeBias: "Engineering",
    defaultSummary: "Live ERP integrations are timing out due to expired or rotated credentials.",
  },
  {
    issueType: "Group consolidation data mismatch",
    product: "AARO",
    category: "Consolidation",
    baseHours: 10,
    slaTargetHours: 16,
    severity: "high",
    routeBias: "Engineering",
    defaultSummary: "Entity-level balances are diverging from consolidated group results.",
  },
  {
    issueType: "FX translation anomaly",
    product: "AARO",
    category: "Consolidation",
    baseHours: 7,
    slaTargetHours: 12,
    severity: "medium",
    routeBias: "Support Operations",
    defaultSummary: "Currency translation rules are applying inconsistent rates across entities.",
  },
  {
    issueType: "Disclosure package validation error",
    product: "AARO",
    category: "Consolidation",
    baseHours: 5,
    slaTargetHours: 10,
    severity: "medium",
    routeBias: "Customer Success",
    defaultSummary: "Disclosure templates are failing validation before submission.",
  },
  {
    issueType: "Forecasting model access",
    product: "Mercur",
    category: "Access",
    baseHours: 3,
    slaTargetHours: 8,
    severity: "medium",
    routeBias: "Customer Success",
    defaultSummary: "Finance planners are blocked from opening shared forecasting models.",
  },
  {
    issueType: "Driver-based planning latency",
    product: "Mercur",
    category: "Planning",
    baseHours: 6,
    slaTargetHours: 10,
    severity: "medium",
    routeBias: "Engineering",
    defaultSummary: "Complex driver-based calculations are lagging during scenario runs.",
  },
  {
    issueType: "Board report export timeout",
    product: "Mercur",
    category: "Planning",
    baseHours: 4,
    slaTargetHours: 8,
    severity: "low",
    routeBias: "Customer Success",
    defaultSummary: "Board-ready export jobs are timing out during PDF or Excel generation.",
  },
  {
    issueType: "Role provisioning drift",
    product: "Mercur",
    category: "Access",
    baseHours: 5,
    slaTargetHours: 8,
    severity: "medium",
    routeBias: "Customer Success",
    defaultSummary: "Permission sets are no longer aligned with operating model changes.",
  },
  {
    issueType: "Data import schema conflict",
    product: "AARO",
    category: "Integration",
    baseHours: 9,
    slaTargetHours: 14,
    severity: "high",
    routeBias: "Engineering",
    defaultSummary: "Source system extracts no longer match expected import mappings.",
  },
  {
    issueType: "Intercompany reconciliation exception",
    product: "Aico",
    category: "Close",
    baseHours: 7,
    slaTargetHours: 10,
    severity: "high",
    routeBias: "Support Operations",
    defaultSummary: "Intercompany balances are failing automatic reconciliation rules.",
  },
];

export const SUPPORT_CONTEXT_NOTES = [
  "Debayan-led AI support transformation lens",
  "Multi-country, multi-product operating model",
  "Zendesk + Salesforce case simulation",
];
